apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mod-web-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/chrisbeech105/example-web-openshift
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: openshift/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: mod-web-app:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret